In [1]:
import pandas as pd

In [6]:
Healthcare_data=pd.read_excel("Patient_Details.xlsx")

In [7]:
Healthcare_data.isna().sum()

PatientID           0
patientFirstName    0
patientLastName     0
patientEmail        0
PatientGender       0
PatientAge          0
patientCountry      0
patientCity         0
patientState        0
dtype: int64

In [9]:
pd.read_csv("Hospital_General_Information.csv")

,index,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,...,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote,Location
0,0,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,...,NaN,Same as the National average,NaN,Same as the National average,NaN,Above the National average,NaN,Below the National average,NaN,"2505 U S HIGHWAY 431 NORTH\nBOAZ, AL 35957\n"
1,1,10032,WEDOWEE HOSPITAL,209 NORTH MAIN STREET,WEDOWEE,AL,36278,RANDOLPH,2563572111,Acute Care Hospitals,...,NaN,Not Available,Results are not available for this reporting p...,Same as the National average,NaN,Same as the National average,NaN,Not Available,Results are not available for this reporting p...,"209 NORTH MAIN STREET\nWEDOWEE, AL 36278\n"
2,2,10131,CRESTWOOD MEDICAL CENTER,ONE HOSPITAL DR SE,HUNTSVILLE,AL,35801,MADISON,2568823100,Acute Care Hospitals,...,NaN,Same as the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,"ONE HOSPITAL DR SE\nHUNTSVILLE, AL 35801\n"
3,3,20001,PROVIDENCE ALASKA MEDICAL CENTER,BOX 196604,ANCHORAGE,AK,99508,ANCHORAGE,9072123675,Acute Care Hospitals,...,NaN,Below the National average,NaN,Below the National average,NaN,Below the National average,NaN,Same as the National average,NaN,"BOX 196604\nANCHORAGE, AK 99508\n"
4,4,20018,YUKON KUSKOKWIM DELTA REG HOSPITAL,PO BOX 287,BETHEL,AK,99559,BETHEL,9075436300,Acute Care Hospitals,...,NaN,Below the National average,NaN,Below the National average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"PO BOX 287\nBETHEL, AK 99559\n"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4813,4813,501333,KITTITAS VALLEY COMMUNITY HOSPITAL,603 SOUTH CHESTNUT,ELLENSBURG,WA,98926,KITTITAS,5099629841,Critical Access Hospitals,...,NaN,Above the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,"603 SOUTH CHESTNUT\nELLENSBURG, WA 98926\n(46...."
4814,4814,450827,KELL WEST REGIONAL HOSPITAL,5402 KELL WEST BOULEVARD,WICHITA FALLS,TX,76310,WICHITA,9406925888,Acute Care Hospitals,...,NaN,Above the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,Same as the National average,NaN,"5402 KELL WEST BOULEVARD\nWICHITA FALLS, TX 76..."
4815,4815,501310,NEWPORT COMMUNITY HOSPITAL,714 WEST PINE STREET,NEWPORT,WA,99156,PEND OREILLE,5094472441,Critical Access Hospitals,...,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"714 WEST PINE STREET\nNEWPORT, WA 99156\n(48.1..."
4816,4816,670107,BAYLOR EMERGENCY MEDICAL CENTER,12500 SOUTH FREEWAY SUITE 100,BURLESON,TX,76028,JOHNSON,2142946250,Acute Care Hospitals,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Same as the National average,NaN,Not Available,Results are not available for this reporting p...,"12500 SOUTH FREEWAY SUITE 100\nBURLESON, TX 76..."
4817,4817,450213,UNIVERSITY HEALTH SYSTEM,4502 MEDICAL DR,SAN ANTONIO,TX,78229,BEXAR,2103584000,Acute Care Hospitals,...,NaN,Same as the National average,NaN,Same as the National average,NaN,Below the National average,NaN,Below the National average,NaN,"4502 MEDICAL DR\nSAN ANTONIO, TX 78229\n(29.50..."

In [10]:
pd.read_csv("hospital_locations.csv")

,index,X,Y,OBJECTID,ID,NAME,ADDRESS,CITY,STATE,ZIP,...,VAL_DATE,WEBSITE,STATE_ID,ALT_NAME,ST_FIPS,OWNER,TTL_STAFF,BEDS,TRAUMA,HELIPAD
0,0,-1.322651e+07,4.049626e+06,2,53391362,LOS ROBLES HOSPITAL & MEDICAL CENTER - EAST CA...,150 VIA MERIDA,WESTLAKE VILAGE,CA,91362,...,2014/02/10 00:00:00+00,http://www.losrobleshospital.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,40,NOT AVAILABLE,N
1,1,-1.315620e+07,4.031978e+06,3,11190023,EAST LOS ANGELES DOCTORS HOSPITAL,4060 WHITTIER BOULEVARD,LOS ANGELES,CA,90023,...,2014/02/10 00:00:00+00,http://www.elalax.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,127,NOT AVAILABLE,N
2,2,-1.317190e+07,4.041752e+06,4,17090028,SOUTHERN CALIFORNIA HOSPITAL AT HOLLYWOOD,6245 DE LONGPRE AVENUE,HOLLYWOOD,CA,90028,...,2014/02/10 00:00:00+00,http://sch-hollywood.com/,NOT AVAILABLE,HOLLYWOOD COMMUNITY HOSPITAL OF HOLLYWOOD,6,PROPRIETARY,-999,100,NOT AVAILABLE,N
3,3,-1.313208e+07,4.037270e+06,5,23691706,KINDRED HOSPITAL BALDWIN PARK,14148 FRANCISQUITO AVENUE,BALDWIN PARK,CA,91706,...,2014/02/10 00:00:00+00,http://www.khbaldwinpark.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,95,NOT AVAILABLE,N
4,4,-1.315222e+07,4.009980e+06,6,25190712,LAKEWOOD REGIONAL MEDICAL CENTER,3700 EAST SOUTH STREET,LAKEWOOD,CA,90712,...,2014/02/10 00:00:00+00,http://www.lakewoodregional.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,172,NOT AVAILABLE,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7618,7618,-8.394315e+06,4.678660e+06,7825,196784304,SUN BEHAVIORAL DELAWARE LLC,21655 BIDEN AVE,GEORGETOWN,DE,19947,...,2020/11/02 00:00:00+00,NOT AVAILABLE,NOT AVAILABLE,NOT AVAILABLE,10,NOT AVAILABLE,-999,-999,NOT AVAILABLE,N
7619,7619,-1.087172e+07,3.861479e+06,7826,196784305,TEXAS HEALTH NEIGHBORHOOD CARE & WELLNESS WILL...,101 CROWN POINTE BLVD,WILLOW PARK,TX,76087,...,2021/04/26 00:00:00+00,NOT AVAILABLE,NOT AVAILABLE,NOT AVAILABLE,48,NOT AVAILABLE,-999,-999,NOT AVAILABLE,Y
7620,7620,-1.298899e+07,4.200987e+06,7827,196784306,WEED ARMY COMMUNITY HOSPITAL,N LOOP RD,FORT IRWIN,CA,92310,...,2020/10/30 00:00:00+00,NOT AVAILABLE,NOT AVAILABLE,NOT AVAILABLE,6,GOVERNMENT - FEDERAL,-999,-999,NOT AVAILABLE,Y
7621,7621,-1.086452e+07,3.924259e+06,7828,196784307,WISE REGIONAL HEALTH SYSTEM,2000 FM 51,DECATUR,TX,76234,...,2021/04/26 00:00:00+00,NOT AVAILABLE,NOT AVAILABLE,NOT AVAILABLE,48,NOT AVAILABLE,-999,-999,NOT AVAILABLE,Y
7622,7622,-1.045536e+07,5.143663e+06,7829,196784308,WOODWARD STATE HOSPITAL & SCHOOL,1251 334TH STREET,WOODWARD,IA,50276,...,2020/11/02 00:00:00+00,NOT AVAILABLE,NOT AVAILABLE,NOT AVAILABLE,19,NOT AVAILABLE,-999,-999,NOT AVAILABLE,Y